version: 2.1

commands:
  test:
    steps:
      - checkout
      - run: sudo pip install --only-binary=numpy,scipy -r requirements.txt
      - run: sudo pip install scikit-learn==0.19.2
      - run: sudo pip install pytest mock pylint
      - run: sudo python setup.py clean --all
      - run: sudo pip install -e .[ensemble]
      - run: sudo python -m pytest -rw -v test
  lint:
    steps:
      - run: sudo pip install pylint==2.3.1
      - run: sudo ./lint


jobs:
  test-py37:
    docker:
      - image: circleci/python:3.7
        environment:
          SKLEARN_VERSION: 0.19.2
    steps:
      - test
      - lint
  test-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - test
  test-py35:
    docker:
      - image: circleci/python:3.5
    steps:
      - test
  test-py34:
    docker:
      - image: circleci/python:3.4
    steps:
      - test
  test-py27:
    docker:
      - image: circleci/python:2.7
    steps:
      - test

workflows:
  main:
    jobs:
      - test-py27
      - test-py34
      - test-py35
      - test-py36
      - test-py37
